spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          show_sql: true
