name: Deploy Spring Boot Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd be
          ./gradlew clean build

      - name: Check JAR output
        run: |
          ls -lh be/build/libs/

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./be/build/libs/IssueTracker-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/upload/"

      - name: Move to app.jar on EC2 and clean directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🧹 기존 app.jar 제거"
            rm -rf /home/ubuntu/app.jar

            echo "🔍 JAR 경로 자동 탐색"
            JAR_PATH=$(find /home/ubuntu/upload -name "IssueTracker-0.0.1-SNAPSHOT.jar" | head -n 1)

            echo "👉 발견된 경로: $JAR_PATH"

            if [ -z "$JAR_PATH" ]; then
              echo "❌ JAR 파일을 찾을 수 없습니다"
              exit 1
            fi

            mv "$JAR_PATH" /home/ubuntu/app.jar
            ls -lh /home/ubuntu/app.jar

      - name: Generate .env file on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "📦 .env 파일 생성"
            cat > /home/ubuntu/.env <<EOL
            JWT_ACCESS_KEY=${{ secrets.JWT_ACCESS_KEY }}
            JWT_REFRESH_KEY=${{ secrets.JWT_REFRESH_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            EOL

      - name: Run JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🛑 기존 프로세스 종료"
            pkill -f 'java -jar' || true

            echo "🌍 환경 변수 로딩"
            set -a
            source /home/ubuntu/.env
            set +a

            echo "🚀 JAR 실행"
            nohup java -jar -Dspring.profiles.active=dev /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &

            echo "✅ 배포 완료"
            exit 0
