name: Deploy Spring Boot Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd be
          ./gradlew clean build

      - name: Confirm JAR Build
        run: |
          echo "✅ JAR 파일 확인:"
          ls -lh be/build/libs/

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./be/build/libs/IssueTracker-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/app.jar"

      - name: Confirm JAR Exists on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "📦 복사된 JAR 확인"
            ls -lh /home/ubuntu/
            if [ -f /home/ubuntu/app.jar ]; then
              echo "✅ app.jar 파일 존재함"
            else
              echo "❌ app.jar 복사 실패 또는 디렉토리로 잘못 생성됨"
              exit 1
            fi

      - name: Run JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🛑 기존 프로세스 종료 시도"
            pkill -f 'java -jar' || true

            echo "🚀 새 JAR 실행"
            nohup java -jar -Dspring.profiles.active=dev /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &

            echo "✅ 실행 명령 전송 완료"
            exit 0
