name: Deploy Spring Boot Backend to EC2

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v3

      - name: ☕ Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🏗️ Build with Gradle
        run: |
          cd be
          ./gradlew clean build

      - name: 📦 Check JAR Output
        run: |
          ls -lh be/build/libs/

      - name: 🚚 Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./be/build/libs/IssueTracker-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/upload/"

      - name: 🚀 Run Spring Boot App on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🛑 Stop previous app"
            pkill -f 'java -jar' || true

            echo "🧹 Clean previous app"
            rm -f /home/ubuntu/app.jar
            mv /home/ubuntu/upload/IssueTracker-0.0.1-SNAPSHOT.jar /home/ubuntu/app.jar

            echo "🔑 Writing .env file"
            cat <<EOF > /home/ubuntu/.env
            export JWT_ACCESS_KEY=${{ secrets.JWT_ACCESS_KEY }}
            export JWT_REFRESH_KEY=${{ secrets.JWT_REFRESH_KEY }}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_REGION=${{ secrets.AWS_REGION }}
            export S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
            EOF

            echo "📤 Load environment variables"
            source /home/ubuntu/.env

            echo "🚀 Run Spring Boot"
            nohup java \
              -Dspring.profiles.active=dev \
              -DJWT_ACCESS_KEY=$JWT_ACCESS_KEY \
              -DJWT_REFRESH_KEY=$JWT_REFRESH_KEY \
              -DAWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              -DAWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
              -DAWS_REGION=$AWS_REGION \
              -DS3_BUCKET_NAME=$S3_BUCKET_NAME \
              -jar /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &

            echo "📄 Print last 20 lines of app.log"
            tail -n 20 /home/ubuntu/app.log
