name: Deploy Fullstack App to EC2 (No CodeDeploy)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ☕ Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🧱 Build Frontend
        working-directory: fe
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.FRONTEND_API_BASE_URL }}" > .env.production
          npm install
          npm run build

      - name: 🧱 Build Backend
        working-directory: be
        run: |
          ./gradlew clean build -x test

      - name: 📦 Zip artifacts
        run: |
          mkdir -p deploy_bundle/scripts
          JAR_PATH=$(find be/build/libs -name "*.jar" | head -n 1)
          cp "$JAR_PATH" deploy_bundle/app.jar
          cp -r fe/dist deploy_bundle/frontend
          echo "${{ secrets.EC2_START_SCRIPT }}" > deploy_bundle/scripts/start.sh
          echo "${{ secrets.EC2_STOP_SCRIPT }}" > deploy_bundle/scripts/stop.sh
          chmod +x deploy_bundle/scripts/*.sh
          zip -r deploy.zip deploy_bundle

      - name: 🔐 Copy to EC2 via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deploy.zip"
          target: "/home/ubuntu"

      - name: 🚀 Remote Deploy (unzip + restart)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            unzip -o deploy.zip -d app
            bash app/scripts/stop.sh
            bash app/scripts/start.sh
