name: Deploy Spring Boot Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd be
          ./gradlew clean build

      - name: Check JAR output
        run: |
          ls -lh be/build/libs/

      - name: Copy JAR to EC2 (into /upload dir)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./be/build/libs/IssueTracker-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/upload/"

      - name: Move to app.jar on EC2 and clean directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🧹 기존 app.jar 제거"
            rm -rf /home/ubuntu/app.jar

            echo "📦 JAR 파일 이동"
            mv /home/ubuntu/upload/IssueTracker-0.0.1-SNAPSHOT.jar /home/ubuntu/app.jar

            echo "✅ 최종 파일 확인"
            ls -lh /home/ubuntu/app.jar
            [ -f /home/ubuntu/app.jar ] || exit 1

      - name: Run JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🛑 기존 프로세스 종료"
            pkill -f 'java -jar' || true

            echo "🚀 애플리케이션 실행"
            nohup java -jar -Dspring.profiles.active=dev /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &
            exit 0
