name: Deploy Fullstack App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ☕ Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🪠 Set Frontend Environment
        working-directory: fe
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.FRONTEND_API_BASE_URL }}" > .env.production

      - name: 🧱 Build Frontend
        working-directory: fe
        run: |
          npm install
          npm run build

      - name: 🧱 Build Backend
        working-directory: be
        run: |
          ./gradlew clean bootJar -x test

      # 📦 Prepare Deployment Bundle
      - name: 📦 Prepare Deployment Bundle
        run: |
          mkdir -p bundle/frontend
          mkdir -p bundle/scripts

          # ✅ 가장 최근 jar 하나만 복사
          JAR_PATH=$(find be/build/libs -name "*.jar" -print0 | xargs -0 ls -t | head -n 1)
          cp "$JAR_PATH" bundle/app.jar
      
          # ✅ 프론트엔드 복사
          cp -r fe/dist/* bundle/frontend/
      
          # ✅ 스크립트 복사
          cp deploy/scripts/start.sh bundle/scripts/
          cp deploy/scripts/stop.sh bundle/scripts/
      
          # ✅ .env 파일 생성
          cat <<EOF > bundle/application.env
          JWT_ACCESS_KEY=${{ secrets.JWT_ACCESS_KEY }}
          JWT_REFRESH_KEY=${{ secrets.JWT_REFRESH_KEY }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          S3_URL_NAME=${{ secrets.S3_URL_NAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF
      
          # ✅ zip 압축
          cd bundle
          zip -r ../deploy.zip .

      

      - name: ☁️ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ☁️ Upload to S3 (optional)
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy.zip

      - name: 🚀 Deploy to EC2 and Run
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. 기존 app 디렉토리 제거 후 압축 해제
            rm -rf /home/ubuntu/app
            unzip -o /home/ubuntu/deploy.zip -d /home/ubuntu/app

            # 2. 스크립트 권한 설정 및 실행
            chmod +x /home/ubuntu/app/scripts/*.sh
            bash /home/ubuntu/app/scripts/stop.sh
            bash /home/ubuntu/app/scripts/start.sh

            # 3. 로그 출력
            tail -n 100 /home/ubuntu/app.log
