name: Deploy Fullstack App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ☕ Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🛠 Set Frontend Environment
        working-directory: fe
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.FRONTEND_API_BASE_URL }}" > .env.production

      - name: 🧱 Build Frontend
        working-directory: fe
        run: |
          npm install
          npm run build

      - name: 🧱 Build Backend
        working-directory: be
        run: |
          ./gradlew clean bootJar -x test
          echo "✅ 빌드 완료 JAR 목록:"
          ls -lh build/libs/

      - name: 🧹 Remove Old ZIP if Exists
        run: |
          rm -f deploy.zip

      - name: 📦 Prepare Deployment Bundle
        run: |
          mkdir -p bundle/app/frontend
          mkdir -p bundle/scripts

          echo "✅ 복사 대상 JAR:"
          ls -lh be/build/libs/app.jar || (echo "❌ JAR 없음!" && exit 1)
          cp be/build/libs/app.jar bundle/app/app.jar

          cp -r fe/dist/* bundle/app/frontend/

          cp deploy/scripts/start.sh bundle/scripts/
          cp deploy/scripts/stop.sh bundle/scripts/

          cat <<EOF > bundle/app/application.env
          JWT_ACCESS_KEY=${{ secrets.JWT_ACCESS_KEY }}
          JWT_REFRESH_KEY=${{ secrets.JWT_REFRESH_KEY }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          S3_URL_NAME=${{ secrets.S3_URL_NAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

          cd bundle
          zip -r ../deploy.zip .

      - name: ☁️ Configure AWS Credentials (Optional if using AWS CLI)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🚀 Deploy zip directly to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deploy.zip"
          target: "/home/ubuntu/"

      - name: 🚀 Run Deployment Script on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            unzip -o deploy.zip -d app
            chmod +x app/scripts/*.sh
            bash app/scripts/stop.sh
            bash app/scripts/start.sh
