name: Deploy Fullstack App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ☕ Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🪠 Set Frontend Environment
        working-directory: fe
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.FRONTEND_API_BASE_URL }}" > .env.production

      - name: 🧱 Build Frontend
        working-directory: fe
        run: |
          npm install
          npm run build

      - name: 🧱 Build Backend
        working-directory: be
        run: |
          ./gradlew clean bootJar -x test

      - name: 📦 Bundle for Deployment
        run: |
          mkdir -p bundle/frontend
          mkdir -p bundle/scripts

          # ✅ 환경변수 .env 생성
          echo "JWT_ACCESS_KEY=${{ secrets.JWT_ACCESS_KEY }}" > bundle/.env
          echo "JWT_REFRESH_KEY=${{ secrets.JWT_REFRESH_KEY }}" >> bundle/.env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> bundle/.env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> bundle/.env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> bundle/.env
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> bundle/.env
          echo "S3_URL_NAME=${{ secrets.S3_URL_NAME }}" >> bundle/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> bundle/.env

          # ✅ start.sh, stop.sh 복사 (Git에 있는 파일)
          cp deploy-scripts/start.sh bundle/scripts/start.sh
          cp deploy-scripts/stop.sh bundle/scripts/stop.sh
          chmod +x bundle/scripts/*.sh

          # ✅ 프론트 복사
          cp -r fe/dist/* bundle/frontend/

          # ✅ JAR 복사
          JAR_PATH=$(ls -t be/build/libs/*.jar | head -n 1)
          cp "$JAR_PATH" bundle/app.jar

          # ✅ 압축
          zip -r deploy.zip bundle
