name: Deploy Fullstack App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ☕ Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🛠 Set Frontend Environment
        working-directory: fe
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.FRONTEND_API_BASE_URL }}" > .env.production

      - name: 🧱 Build Frontend
        working-directory: fe
        run: |
          npm install
          npm run build

      - name: 🧱 Build Backend
        working-directory: be
        run: |
          ./gradlew clean build -x test

      - name: 📦 Prepare Deployment Bundle
        run: |
          mkdir -p bundle/app/frontend
          mkdir -p bundle/scripts

          # ✅ JAR 복사
          JAR_PATH=$(find be/build/libs -name "*.jar" | head -n 1)
          cp "$JAR_PATH" bundle/app/app.jar

          # ✅ 프론트엔드 빌드 복사
          cp -r fe/dist/* bundle/app/frontend/

          # ✅ 스크립트 복사
          cp deploy/scripts/start.sh bundle/scripts/
          cp deploy/scripts/stop.sh bundle/scripts/

          # ✅ 환경 변수 템플릿 복사
          cp deploy/application.env bundle/app/application.env

          # ✅ zip 압축
          cd bundle
          zip -r ../deploy.zip .

      - name: ☁️ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ☁️ Upload to S3 (optional)
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy.zip

      - name: 🚀 Deploy to EC2 and Run
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            unzip -o deploy.zip -d app
            chmod +x app/scripts/*.sh
            bash app/scripts/stop.sh
            bash app/scripts/start.sh
