name: Deploy Fullstack App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ☕ Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🧱 Build Frontend
        working-directory: fe
        run: |
          npm install
          npm run build

      - name: 🧱 Build Backend
        working-directory: be
        run: |
          ./gradlew clean bootJar -x test

      - name: 📦 Bundle for Deployment
        run: |
          mkdir -p bundle/frontend
          mkdir -p bundle/scripts

          cp -r fe/dist/* bundle/frontend/
          cp be/build/libs/*.jar bundle/app.jar
          cp deploy/scripts/*.sh bundle/scripts/

          zip -r deploy.zip bundle

      - name: 🚀 Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "deploy.zip"
          target: "/home/ubuntu"

      - name: 💻 Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🛑 기존 프로세스 종료 중..."
            PID=$(pgrep -f 'java -jar')
            if [ -n "$PID" ]; then
              kill -9 $PID
              echo "✅ 종료된 PID: $PID"
            else
              echo "ℹ️ 종료할 프로세스 없음"
            fi

            echo "📦 새 배포 압축 해제..."
            rm -rf /home/ubuntu/app
            unzip -o /home/ubuntu/deploy.zip -d /home/ubuntu/app
            chmod +x /home/ubuntu/app/scripts/*.sh

            echo "🚀 새 애플리케이션 실행..."
            cd /home/ubuntu/app
            nohup java \
              -Dspring.profiles.active=dev \
              -DJWT_ACCESS_KEY=${{ secrets.JWT_ACCESS_KEY }} \
              -DJWT_REFRESH_KEY=${{ secrets.JWT_REFRESH_KEY }} \
              -DAWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -DAWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -DAWS_REGION=${{ secrets.AWS_REGION }} \
              -Dcloud.aws.region.static=${{ secrets.AWS_REGION }} \
              -Dcloud.aws.s3.bucket=${{ secrets.S3_BUCKET_NAME }} \
              -Dcloud.aws.s3.url=${{ secrets.S3_URL_NAME }} \
              -Dspring.datasource.password=${{ secrets.DB_PASSWORD }} \
              -jar app.jar > app.log 2>&1 &

            sleep 3
            echo "📄 서버 로그 출력 시작 (상위 100줄)"
            tail -n 100 /home/ubuntu/app/app.log || echo "⚠️ 로그 파일이 아직 생성되지 않았을 수 있습니다."
