name: Deploy Fullstack App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ☕ Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🛠 Set Frontend Environment
        working-directory: fe
        run: |
          echo "REACT_APP_API_BASE_URL=${{ secrets.FRONTEND_API_BASE_URL }}" > .env.production

      - name: 🧱 Build Frontend
        working-directory: fe
        run: |
          npm install
          npm run build

      - name: 🧱 Build Backend
        working-directory: be
        run: |
          ./gradlew clean build -x test

      - name: 📦 Zip Deployment Files
        run: |
          mkdir -p deploy/app

          # ✅ JAR 자동 탐색 및 복사
          JAR_PATH=$(find be/build/libs -name "*.jar" | head -n 1)
          echo "JAR found: $JAR_PATH"
          cp "$JAR_PATH" deploy/app/app.jar

          # ✅ React 빌드 결과 복사
          cp -r fe/dist deploy/app/frontend

          # ✅ 배포 스크립트 복사만 남기고 appspec.yml은 그대로 둠
          cp deploy/scripts/start.sh deploy/
          cp deploy/scripts/stop.sh deploy/
          touch deploy/application.env

          zip -r deploy.zip deploy
      

      - name: ☁️ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ☁️ Upload to S3
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy.zip

      - name: 🚀 Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secrets.CODEDEPLOY_GROUP_NAME }} \
            --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=deploy.zip \
            --region ${{ secrets.AWS_REGION }}
