name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Frontend
        working-directory: fe
        run: |
          npm install
          npm run build

      - name: Build Backend
        working-directory: be
        run: |
          ./gradlew clean build -x test

      - name: Zip Deployment Files
        run: |
          mkdir -p deploy/app
          cp be/build/libs/*.jar deploy/app/app.jar
          cp -r fe/dist deploy/app/frontend
          cp appspec.yml deploy/
          cp scripts/start.sh deploy/
          cp scripts/stop.sh deploy/
          cp scripts/application.env deploy/  # 더미 .env, 실제는 start.sh에서 Secrets로 채움
          zip -r deploy.zip deploy

      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: aws s3 cp deploy.zip s3://your-bucket-name/deploy.zip

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name your-app-name \
            --deployment-group-name your-deployment-group \
            --s3-location bucket=your-bucket-name,bundleType=zip,key=deploy.zip \
            --region ${{ secrets.AWS_REGION }}
